site_name: A Solution Manual for ESL


site_author: Kungang Zhang
site_description: >-
  Solution for ESL
# Repository
repo_name: YuhangZhou88/ESL_Solution
repo_url: https://github.com/YuhangZhou88/ESL_Solution
edit_uri: ""

# Configuration
theme:
  name: material
  feature:
    - navigation.expand

  # Static files
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    # - navigation.instant
    # - navigation.sections
    - navigation.tabs
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: light green
      accent: light green
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo

# Extensions
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
  - pymdownx.details

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

copyright: 'Copyright &copy; 2022 Kungang Zhang'  

extra:
  analytics:
    provider: google
    property: G-DR64J9QRNF
